name: rastreo_app
description: "Una nueva aplicación Flutter para rastreo de envíos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_dotenv: ^5.0.2

  # Notificaciones - updated to latest version
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Conectividad Bluetooth
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.0

  # Animaciones - updated version
  flutter_animate: ^4.3.0

  # Iconos
  cupertino_icons: ^1.0.6
  http: ^1.2.1

  # Google Maps Flutter
  google_maps_flutter: ^2.2.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true # Habilita la generación de código para l10n
  uses-material-design: true

  # Declaración de assets (imágenes)
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
